# Generated by Django 3.1.4 on 2020-12-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrantHolders', '0005_grantholders_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grantholders',
            name='degree',
            field=models.CharField(choices=[('Бакалавр', 'Бакалавр'), ('Магистратура', 'Магистратура'), ('Доктарантура', 'Доктарантура')], default='Бакалавр', max_length=30),
        ),
    ]
