# Generated by Django 3.1.4 on 2021-01-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrantHolders', '0007_auto_20201229_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantholders',
            name='expected_result_en',
            field=models.TextField(null=True, verbose_name='Күтілетін нәтиже'),
        ),
        migrations.AddField(
            model_name='grantholders',
            name='expected_result_kk',
            field=models.TextField(null=True, verbose_name='Күтілетін нәтиже'),
        ),
        migrations.AddField(
            model_name='grantholders',
            name='expected_result_ru',
            field=models.TextField(null=True, verbose_name='Күтілетін нәтиже'),
        ),
        migrations.AddField(
            model_name='grantholders',
            name='novelty_scientific_en',
            field=models.TextField(null=True, verbose_name='Ғылыми жұмыстың жаңалығы'),
        ),
        migrations.AddField(
            model_name='grantholders',
            name='novelty_scientific_kk',
            field=models.TextField(null=True, verbose_name='Ғылыми жұмыстың жаңалығы'),
        ),
        migrations.AddField(
            model_name='grantholders',
            name='novelty_scientific_ru',
            field=models.TextField(null=True, verbose_name='Ғылыми жұмыстың жаңалығы'),
        ),
        migrations.AddField(
            model_name='grantholders',
            name='project_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Жобаның тақырыбы'),
        ),
        migrations.AddField(
            model_name='grantholders',
            name='project_name_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Жобаның тақырыбы'),
        ),
        migrations.AddField(
            model_name='grantholders',
            name='project_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Жобаның тақырыбы'),
        ),
        migrations.AddField(
            model_name='grantholders',
            name='purpose_project_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Жобаның мақсаты'),
        ),
        migrations.AddField(
            model_name='grantholders',
            name='purpose_project_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Жобаның мақсаты'),
        ),
        migrations.AddField(
            model_name='grantholders',
            name='purpose_project_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Жобаның мақсаты'),
        ),
        migrations.AddField(
            model_name='grantholders',
            name='ways_project_en',
            field=models.TextField(null=True, verbose_name='Жоба мақсатына жету жолдары'),
        ),
        migrations.AddField(
            model_name='grantholders',
            name='ways_project_kk',
            field=models.TextField(null=True, verbose_name='Жоба мақсатына жету жолдары'),
        ),
        migrations.AddField(
            model_name='grantholders',
            name='ways_project_ru',
            field=models.TextField(null=True, verbose_name='Жоба мақсатына жету жолдары'),
        ),
    ]
